#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        javax.cache:
#          https://stackoverflow.com/questions/56294726/spring-boot-2-0-hibernate-5-ehcache-3-with-jcache
          missing_cache_strategy: create
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
        time_zone: UTC
#        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_structured_entries: true
          region:
            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
  datasource:
    # ImMemory
    url: jdbc:h2:mem:voting
    port: "9092"
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    username: sa
    password:

  # Jackson Serialization Issue Resolver
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
#    serialization:
#      write-dates-as-timestamps: false
#    default-property-inclusion: non_null

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
  #  https://stackoverflow.com/a/49073342
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache.xml

  sql:
    init:
      mode: always
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
      date: iso

logging:
  level:
#    org:
#      hibernate:
#        type: trace
    root: WARN
    ru.khalitovaae.restaurantvoting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
#    org.hibernate.stat: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

vote:
  deadline: "11:00:00"